# Buat function kalkulator dengan operator
### 'x' sebagai kali
### ':' sebagai bagi
### '+' sebagai tambah
### '-'sebagai kurang
### '^' sebagai pangkat

In [1]:
c = '34'
c.isnumeric()

True

In [2]:
try:
  int('sd')
except:
  print('bukan integer')

bukan integer


In [4]:
def calc(a,b,c):
  if(a.isnumeric() == True) and (c.isnumeric() == True):
    a = int(a)
    b = int(c)
    if b == 'x':
      print('Hasil dari ',a,b,c, 'adalah ', a*c)
    elif b == '+':
      print('Hasil dari ',a,b,c, 'adalah ',a+c)
    elif b == ':':
      print('Hasil dari ',a,b,c, 'adalah ',a/c)
    elif b == '-':
      print('Hasil dari ',a,b,c, 'adalah ',a-c)
    elif b == '^':
      print('Hasil dari ',a,b,c, 'adalah ',a**c)
    else:
      print('operator', b, 'tidak ditemukan')
  else:
    print('salah')

a = (input('masukkan angka1 = '))
b = (input('masukkan operator = '))
c = (input('masukkan angka2 = '))

calc(a,b,c)

masukkan angka1 = 10
masukkan operator = +
masukkan angka2 = 10
operator 10 tidak ditemukan


# Import Numpy

In [5]:
import numpy as np

In [ ]:
c = np.array([1,2,3])

In [7]:
print(c)

10


# One dimensional array

## indexing dan slicing

In [8]:
c[1]

'0'

In [10]:
array_1 = np.array([1,2,3,4,5,6,7,8])

In [11]:
array_1[3:]

array([4, 5, 6, 7, 8])

In [13]:
array_1.shape

(8,)

# 2 dimensional array consist of list of list

In [14]:
list_of_list = [[1,2,3], [4,5,6], [7,8,9]]
array_2 = np.array(list_of_list)
array_2
print(array_2.shape)

(3, 3)


In [16]:
list_of_list_2 = [[1,2,3], [3,4], [5,6]]
array_3 = np.array(list_of_list_2)
print(array_3.shape)
array_3

(3,)


<ipython-input-16-92f2fd8649df>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array_3 = np.array(list_of_list_2)


array([list([1, 2, 3]), list([3, 4]), list([5, 6])], dtype=object)

# Creating Array

In [17]:
# np.zeros
print(np.zeros(8))
print(np.zeros([3,2]))

[0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
# np.ones
print(np.ones(4))
print(np.ones([4,2]))

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [19]:
# np.empty
np.empty(5)
np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
# np_arange
print(np.arange(10))
print(np.arange(0,10,2))

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [21]:
np.arange(0,30,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [22]:
c = np.array([1,2,3,4,5,6,7,8,9])

#append
print(np.append(c,[10,11]))

#delete
print(np.delete(c,2))

#sort
print(np.sort(c))

[ 1  2  3  4  5  6  7  8  9 10 11]
[1 2 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [23]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
c = np.array([1,2,3,4,5,6,7,8,9,10])
d = np.zeros((2,2))

#ndim
print(c.ndim)
print(d.ndim)

#size
print(c.size)
print(d.size)

#reshape
# print(c[:-1].reshape(3,4))

1
2
10
4


In [26]:
array_3 = np.array([[1,2,3,4]])
array_4 = np.array([[5,6,7,8]])

np.vstack([array_3,array_4])
print(np.vstack([array_3,array_4]))

[[1 2 3 4]
 [5 6 7 8]]


In [27]:
array_5 = np.array([1,2,3,4])
array_6 = np.array([5,6,7,8])
np.vstack([array_5,array_6])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [28]:
np.append(array_3,[5,6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
# np.newaxis
array_4 = np.array([4,5,6])
array_4[np.newaxis]
print(array_4[:,np.newaxis].shape)

(3, 1)


In [30]:
# np.newaxis_dims
array_7 = np.array([3,4,5,6,7,8,9])
array_8 = np.expand_dims(array_7, axis=1)
array_9 = np.expand_dims(array_7, axis=0)
print(array_8)
print(array_8.shape)
print(array_9)
print(array_9.shape)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(7, 1)
[[3 4 5 6 7 8 9]]
(1, 7)


# Operasi Matematika pada array sifatnya broadcast

In [31]:
array_7 = np.array([3,4,5,6,7,8,9])
array_7*2

array([ 6,  8, 10, 12, 14, 16, 18])

In [34]:
array_10 = np.array([[1,2,3],[4,5,6]])
array_10-4

array([[-3, -2, -1],
       [ 0,  1,  2]])

# Filter Array

In [35]:
array_7 = np.array([3,4,5,6,7,8,9])
print(array_7[array_7>5])
print(array_7[array_7==8])
print(array_7[array_7<=4])

[6 7 8 9]
[8]
[3 4]


In [38]:
array_11 = np.array([[3,5,7],[8,9,10],[-1,-2,-3]])
array_11.shape
print(array_11[array_11>5])

[ 7  8  9 10]


# hstack, vstack, hsplit, vsplit

In [39]:
#stack
array_14 = np.array([3,4,5,6,7])
array_15 = np.array([7,8,9,10,11])
print('Stack secara vertical')
print(np.vstack([array_14,array_15]))
print('stack secara horizontal')
print(np.hstack([array_14,array_15]))

Stack secara vertical
[[ 3  4  5  6  7]
 [ 7  8  9 10 11]]
stack secara horizontal
[ 3  4  5  6  7  7  8  9 10 11]


In [40]:
#hsplit
array_16 = np.array([3,4,5,6,7,8])
array_split = np.hsplit(array_16,2)
(array_split)

[array([3, 4, 5]), array([6, 7, 8])]

In [41]:
#vsplit
array_19 = np.array([[1,2,3,4],[4,5,6,7]])
print(array_19.shape)
print('horizontal split')
print(np.hsplit(array_19,2))
print('vertical split')
print(np.vsplit(array_19,2))

(2, 4)
horizontal split
[array([[1, 2],
       [4, 5]]), array([[3, 4],
       [6, 7]])]
vertical split
[array([[1, 2, 3, 4]]), array([[4, 5, 6, 7]])]


# Operasi Aritmetik antar 2 array

In [43]:
array_a = np.array([1,2,3])
array_b = np.array([3,4,5])
print(array_a+array_b)

[4 6 8]


In [44]:
array_c = np.array([[1,2,3], [4,5,6]])
array_d = np.array([[6,7,8], [9,10,11]])
print(array_c-array_d)

[[-5 -5 -5]
 [-5 -5 -5]]


# Transposing

In [45]:
array_c = np.array([[5,2,3], [4,5,6]])
print(array_c)
print(array_c.shape)

[[5 2 3]
 [4 5 6]]
(2, 3)


In [46]:
print(array_c.T)
print(array_c.T.shape)

[[5 4]
 [2 5]
 [3 6]]
(3, 2)


# Numpy Math Formulas

In [47]:
array_random = np.random.random([3,2]) * 100
print(array_random)
np.sum(array_random)

[[ 5.64299732 45.24995839]
 [64.16637146  5.24887038]
 [62.04475309 60.73478791]]


243.08773854404637

In [48]:
np.square(9)

81

In [50]:
np.sqrt(9)

3.0

In [52]:
a = np.log(1000000)
print(a)

13.815510557964274


In [53]:
np.exp(a)

999999.9999999995

# Prime Number Generator Based on Interval

In [54]:
# First, we will take the input:
lower_value = int(input("Please, Enter the lowest range value: "))
upper_value = int(input("Please, Enter the upper range value: "))

print("The prime numbers in the range are: ")
for number in range(lower_value,upper_value):
  if number > 1:
    for i in range(2, number):
      if(number% i) == 0:
        break
    else:
      print(number)

Please, Enter the lowest range value: 12
Please, Enter the upper range value: 15
The prime numbers in the range are: 
13


In [56]:
print('saadfs\n fdf')

saadfs
 fdf


In [57]:
for i in range(5):
  print(i)

0
1
2
3
4


In [60]:
import numpy as np
a = np.array([3,2,1])

In [61]:
a[0]

3

In [62]:
np.empty((2,2))

array([[3.5e-323, 4.0e-323],
       [4.4e-323, 4.9e-323]])

In [63]:
np.arange(0,7,2)

array([0, 2, 4, 6])

In [64]:
a = np.array([1,2,3,4])

In [65]:
a

array([1, 2, 3, 4])

In [66]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4]])

In [68]:
b = np.expand_dims(a,axis=0)

In [69]:
b

array([[1, 2, 3, 4]])

In [70]:
c = np.array([[1,2,3], [3,4,5], [6,7,8]])
c
d = c.copy()

In [71]:
c[c>2]

array([3, 3, 4, 5, 6, 7, 8])

In [72]:
np.vstack([c,d])

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8],
       [1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

# Bilangan prima adalah bilangan yang hanya bisa dibagi 1 dan dirinya sendiri

In [73]:
lower_limit = int(input('Lower Limit :'))
upper_limit = int(input("Upper Limit :"))
print(lower_limit, 'sampai',upper_limit)
for num in range(lower_limit,upper_limit+1):
    if num > 1:
        for i in range(2,num):#Filtering buat bilangan prima
            if (num%i)==0:
                break 
        else:
            print(num) #untuk kita dapat bilangan prima kondisi (num%i)==0 harus dilanggar

Lower Limit :12
Upper Limit :10
12 sampai 10
