In [21]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

In [22]:
x = [8,1,2.5,4,28]
x_with_nan = [8,1,2.5, np.nan,4.28]
print(x)
print(x_with_nan)


[8, 1, 2.5, 4, 28]
[8, 1, 2.5, nan, 4.28]


In [23]:
# buat array(y) dan series(z) dari x
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

print(y)
print(y_with_nan)
print(z)
print(z_with_nan)

[ 8.   1.   2.5  4.  28. ]
[8.   1.   2.5   nan 4.28]
0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64
0    8.00
1    1.00
2    2.50
3     NaN
4    4.28
dtype: float64


In [24]:
z_with_nan.isna()

0    False
1    False
2    False
3     True
4    False
dtype: bool

# Central Tendency

*   Mean
*   Weighted mean
*   Geometric
*   Harmonic mean
*   Median
*   Mode





# Aritmatic Mean

1.   x itu list
2.   y itu array
2.   z itu series



In [25]:
sum(x)

43.5

In [26]:
len(x)

5

In [27]:
mean_x = sum(x)/len(x)
mean_x

8.7

In [28]:
mean_stats = statistics.mean(x)
print(mean_stats)

8.7


In [29]:
mean_np = np.mean(x)
print(mean_np)

8.7


In [30]:
y.mean()

8.7

In [31]:
z

0     8.0
1     1.0
2     2.5
3     4.0
4    28.0
dtype: float64

In [32]:
z.mean()

8.7

In [33]:
y_with_nan.mean()

nan

In [34]:
np.mean(y_with_nan)

nan

In [35]:
np.nan*3

nan

In [36]:
# get mean without considering NaN values
np.nanmean(y_with_nan) 

3.9450000000000003

In [37]:
# series langsung merata-ratakan tanpa mempertimbangkan NaN values
z_with_nan.mean() 

3.9450000000000003

In [38]:
z_with_nan

0    8.00
1    1.00
2    2.50
3     NaN
4    4.28
dtype: float64

# Weighted Mean
## Rata-rata dengan menghitung pembobotan

In [42]:
# metrics
x = [8,1,2.5,4,28] 

#weightages
w = [0.1,0.2,0.3,0.25,0.15] 

# convert jadi array
y,z,w = np.average(x),pd.Series(x),np.array(w)

# wmean = np.average(y, weights=w)
# print(wmean)

In [43]:
# manual calculation

wmean_manual = sum(w[i] * x[i] for i in range(len(x)))/sum(w)
print(wmean_manual)

6.95


In [44]:
sum(w)

1.0

# Harmonic Mean
## Sering digunakan untuk rata-rata rate (10/km, 100kg/hari, 1000000 orang/tahun)

In [45]:
speed = [60,20]
hmean_speed = len(speed)/sum(1/item for item in speed)
hmean_speed

30.0

In [46]:
# hmean dengan library 1
hmean_speed_stats = statistics.harmonic_mean(speed)
hmean_speed_stats

30.0

In [47]:
# hmean dengan library 2
hmean_speed_stats2 = scipy.stats.hmean(x)
hmean_speed_stats2

2.7613412228796843

In [48]:
hmean = len(x) / sum(1/item for item in x)
hmean

2.7613412228796843

In [49]:
x

[8, 1, 2.5, 4, 28]

In [50]:
for item in x:
  print(1/item)

0.125
1.0
0.4
0.25
0.03571428571428571


In [51]:
sum(1/item for item in x)

1.8107142857142857

In [52]:
# hmean dengan library
hmean_stats = statistics.harmonic_mean(x)
hmean_stats

2.7613412228796843

# Geometric Mean

Perusahaan berdiri pada tahun 2017
*   Tahun 2017 omsetnya 1000
*   Tahun 2018 naik 30%
*   Tahun 2019 naik 50%
*   Tahun 2020 naik 40%




In [53]:
 x = 1000
 x *= 1.3 # 1300
 x *= 1.5 # 1950
 x *= 1.4 # 2730
 x

2730.0

In [54]:
# aritmatic mean
(30+50+40)/3

40.0

In [55]:
x = 1000
x *= 1.4
x *= 1.4
x *= 1.4
x

2743.9999999999995

In [56]:
# geometric mean
gmean = ((30*50*40)**(1/3))    
gmean

39.148676411688626

In [57]:
x = 1000
x *= 1.3915
x *= 1.3915
x *= 1.3915
x

2694.322835875

In [58]:
# geomatric mean menggunakan library scipy
scipy.stats.gmean([30,40,50]) 

39.14867641168864

# Median

In [59]:
# ganjil
a = [1,2,4,8,9]

n = len(a)
n

5

In [60]:
median = a[2]
median

4

In [61]:
# genap
a = [1,2,4,8]
a = len(a)
(a+1)/2
median = (2+4)/2
median


3.0

In [62]:
# menggunaka numpy
x = [8,1,2.5,4,28]
c = [2,3,4,5]
np.median(x)
np.median(c)

3.5

In [63]:
# pembuktian manual
def median_function(x):
  n = len(x)
  if n%2 == 1: # ganjil
    median_ = sorted(x)[round(0.5*(n-1))] # ambil median
  else : # genap
    x_ord, index = sorted(x), round(0.5*n)
    median_ = 0.5* (x_ord[index-1]+x_ord[index])
  return median_

In [64]:
median_function(x)

4

In [65]:
median_function(c)

3.5

In [66]:
sorted(x)

[1, 2.5, 4, 8, 28]

In [67]:
n = len(x)
round(0.5*(n-1))

2

In [68]:
n

5

In [69]:
7%2

1

In [70]:
6%2

0

# Mode / Modus
Nilai yang paling sering banyak muncul/frekuensi paling tinggi

In [71]:
u = [2,3,2,8,12]

mode_ = max((u.count(i),i)for i in set(u))[1]

In [72]:
statistics.mode(u)

2

In [73]:
scipy.stats.mode(u)[0][0]

<ipython-input-73-d8f8f9254a13>:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  scipy.stats.mode(u)[0][0]


2

In [74]:
scipy.stats.mode(u)[0][0]

<ipython-input-74-d8f8f9254a13>:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  scipy.stats.mode(u)[0][0]


2

In [75]:
mode_lib = scipy.stats.mode(u)[0][0]

<ipython-input-75-3d332761fc48>:1: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode_lib = scipy.stats.mode(u)[0][0]


In [76]:
print(mode_lib)
# print(mode_lib.mode) 
# print(mode_lib.count)


2


In [77]:
u

[2, 3, 2, 8, 12]

In [78]:
u_series = pd.Series(u)
u_series.mode()

0    2
dtype: int64

In [79]:
u_array = np.array(u)
statistics.mode(u_array)

2

In [80]:
v = pd.Series([1,2,3,3,3,np.nan])
v.mode()

0    3.0
dtype: float64

In [81]:
statistics.mode(v)

3.0

In [82]:
h = [1,2,3,3,3,np.nan,np.nan,np.nan,np.nan]
statistics.mode(h)

nan

In [83]:
set([1,1,1,2,3,4,5])

{1, 2, 3, 4, 5}

In [84]:
u.count(12)

1

## Series akan mengabaikan NaN dan List akan mempertimbangkan NaN

# Measures of Variability

## Variance 

In [85]:
x

[8, 1, 2.5, 4, 28]

In [86]:
n = len(x)
mean_var = np.mean(x)
var_ = sum((item-mean_var)**2 for item in x)/(n-1)
var_

123.19999999999999

In [89]:
# variance w/ statistics library 
var_stat = statistics.variance(x)
var_stat

123.2

In [90]:
# variance w/ numpy
var_np = np.var(x,ddof=1)
var_np

123.19999999999999

In [91]:
# variance using series function
z = pd.Series(x)
z.var()

123.19999999999999

# Standar Deviasi
## Hitung variance dan standar deviasi

In [92]:
# dengan menggunakan library

x = [1,2,3,6,7,8,30,40,50]

std_dev = statistics.stdev(x)
print("Standar Deviasi dri x adalah : ",std_dev)

variance = statistics.variance(x)
print("Variasi dari x adalah ", variance)

Standar Deviasi dri x adalah :  18.58090417606205
Variasi dari x adalah  345.25000000000006


In [94]:
# dengan menggunakan manual
x = [1,2,3,6,7,8,30,40,50]
n = len(x)

mean = sum(x)/n
var = sum((item-mean)**2 for item in x)/(n-1)
sd_ = var_**(1/2)

print(var_)
print(sd_)

123.19999999999999
11.099549540409285


In [95]:
x = [8,1,2.5,4,28]

In [96]:
var_np

123.19999999999999

In [97]:
stdev = var_np**(1/2)

In [98]:
stdev

11.099549540409285

In [99]:
stdev = np.sqrt(var_np)
stdev

11.099549540409285

In [100]:
# stdev with statistics library
stdev = statistics.stdev(x)
stdev

11.099549540409287

In [102]:
stdev - np.std(x, ddof=1)
stdev

11.099549540409287

# SKewness

In [103]:
x

[8, 1, 2.5, 4, 28]

In [106]:
n = len(x)
mean = np.mean(x)
stdev = statistics.stdev(x)
skew_ = (sum((item - mean)**3 for item in x))*n / ((n-1)*(n-2)*(stdev**3))
skew_

1.947043227390592

In [108]:
scipy.stats.skew(x,bias=False)

1.9470432273905927

In [109]:
z = pd.Series(x)
z.skew()

1.9470432273905924

In [110]:
scipy.stats.skew(x_with_nan)

nan

In [112]:
z_with_nan = pd.Series(x_with_nan)
z_with_nan.skew()

0.9257784636185135

In [113]:
scipy.stats.skew(z_with_nan)

nan

# Percentiles

In [114]:
x = [-5,-1.1,0.1,2,8,12,8,21,25.8,41]
np.percentile(x,5)

-3.245

In [115]:
np.percentile(x,0)

-5.0

In [116]:
np.percentile(x,90)

27.319999999999997

In [117]:
statistics.quantiles(x,n=2)

[8.0]

In [118]:
statistics.quantiles(x,n=4)

[-0.2, 8.0, 22.2]

In [119]:
statistics.quantiles(x,n=4,method='inclusive')

[0.575, 8.0, 18.75]

In [120]:
x

[-5, -1.1, 0.1, 2, 8, 12, 8, 21, 25.8, 41]

In [121]:
np.quantile(x,0)

-5.0

In [122]:
np.quantile(x,1)

41.0

In [123]:
np.quantile(x,0.5)

8.0

In [124]:
x

[-5, -1.1, 0.1, 2, 8, 12, 8, 21, 25.8, 41]

In [125]:
x_with_nan = [-5, -1.1, np.nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]
x_with_nan

[-5, -1.1, nan, 0.1, 2, 8, 12.8, 21, 25.8, 41]

In [126]:
np.quantile(x_with_nan,0)

nan

In [127]:
np.quantile(x_with_nan,0.5)

nan

In [128]:
x

[-5, -1.1, 0.1, 2, 8, 12, 8, 21, 25.8, 41]

In [129]:
np.quantile(x,[0.25,0.5,0.75])

array([ 0.575,  8.   , 18.75 ])

In [130]:
statistics.quantiles(x,n=4,method='inclusive')

[0.575, 8.0, 18.75]

In [131]:
np.percentile(x,[25,50,75])

array([ 0.575,  8.   , 18.75 ])

# Range (nilai Max - nilai Min)

In [132]:
x

[-5, -1.1, 0.1, 2, 8, 12, 8, 21, 25.8, 41]

In [133]:
np.ptp(x)

46.0

In [135]:
np.max(x)

41.0

In [136]:
np.min(x)

-5.0

In [137]:
np.amax(x) - np.amin(x)

46.0

# Interquartile Range (Q3-Q1) (biasanya digunakan untuk mendeteksi outlier)

In [138]:
x

[-5, -1.1, 0.1, 2, 8, 12, 8, 21, 25.8, 41]

In [142]:
quartiles = np.quantile(x,[0.25,0.75])
IQR = quartiles[1] - quartiles[0]
IQR

18.175

# Summary of Desc. Stats

In [143]:
x

[-5, -1.1, 0.1, 2, 8, 12, 8, 21, 25.8, 41]

In [144]:
result = scipy.stats.describe(x,ddof=1,bias=False)
result

DescribeResult(nobs=10, minmax=(-5.0, 41.0), mean=11.18, variance=204.43733333333336, skewness=1.0597458790815801, kurtosis=0.6706212180772724)

In [145]:
(result.variance)**(1/2)

14.29815838957358

In [146]:
result.minmax[1]-result.minmax[0]

46.0

In [147]:
result.skewness

1.0597458790815801

In [149]:
z = pd.Series(x)
z

0    -5.0
1    -1.1
2     0.1
3     2.0
4     8.0
5    12.0
6     8.0
7    21.0
8    25.8
9    41.0
dtype: float64

In [150]:
z.describe()

count    10.000000
mean     11.180000
std      14.298158
min      -5.000000
25%       0.575000
50%       8.000000
75%      18.750000
max      41.000000
dtype: float64

# Correlation

In [151]:
x = list(range(-10,11))
y = [0,2,2,2,2,3,3,6,7,4,7,6,6,9,4,5,5,10,11,12,14]
x_ar, y_ar = np.array(x),np.array(y)
x_s,y_s = pd.Series(x),pd.Series(y)

In [152]:
len(x) == len(y)

True

# Covariance

In [155]:
n = len(x)
mean_x = np.mean(x)
mean_y = np.mean(y)

cov_xy = (sum((x[item]-mean_x)*(y[item]-mean_y) for item in range(n)))/(n-1)
cov_xy

19.95

# Covariance Matrix Formula

In [156]:
cov_matrix = np.cov(x,y)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

In [157]:
np.var(y,ddof=1)

13.914285714285711

In [158]:
cov_xy = cov_matrix[1,0]
cov_xy

19.95

In [159]:
cov_xy = cov_matrix[1,0]
cov_xy

19.95

# Coviance Coefficient

In [160]:
var_x = np.var(x,ddof=1)
var_y = np.var(y,ddof=1)
cov_xy
std_x = var_x**(1/2)
std_y = var_y**(1/2)
r = cov_xy / (std_x**std_y)
r

0.02202477048576318

In [161]:
r,p = scipy.stats.pearsonr(x,y)
r

0.8619500056316061

In [162]:
p

5.122760847201132e-07